
parameters:
  token_file: /var/storage/token

services:
  _defaults:
    autowire: true
    autoconfigure: true

  MetricsAPI\:
    resource: '../src/*'
    exclude: '../src/{Domain/Post.php,Domain/RunningAvg.php,Domain/AvgPerUser.php,Domain/AggregatedCollection.php,Tests}'

  GuzzleHttp\ClientInterface:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%env(SUPERMETRICS_API_BASE_URL)%'
        timeout: 10.0

  MetricsAPI\Infrastructure\SupermetricsApi\TokenRequest:
    class: MetricsAPI\Infrastructure\SupermetricsApi\TokenRequest
    arguments:
      $clientId: '%env(SUPERMETRICS_API_CLIENT_ID)%'
      $name: '%env(SUPERMETRICS_API_USER_NAME)%'
      $email: '%env(SUPERMETRICS_API_USER_EMAIL)%'

  MetricsAPI\Infrastructure\SupermetricsApi\TokenStorage:
    class: MetricsAPI\Infrastructure\SupermetricsApi\TokenStorage\FileStorage
    arguments:
      $filePath: '%token_file%'

  MetricsAPI\Infrastructure\Console\Command\GenerateReport:
    public: true